services:
  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: todo_db
    ports:
      - 5432:5432
    volumes:
      - ./backend/todo_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  todo_data:
