name: todo-backend-webapp | deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/main_todo-backend-webapp.yml
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/main_todo-backend-webapp.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install, build, and test
        working-directory: ./backend
        run: |
          npm i @nestjs/core
          npm i @nestjs/platform-express
          npm i @nestjs/swagger
          npm i @nestjs/config
          npm i @nestjs/common
          npm i @nestjs/typeorm
          npm i -g @nestjs/cli
          npm i -g npm
          npm ci
          npm run build
          npm run test

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip -r release.zip . -x "*.git*" "test/*" "*.github/*" "*.env" "*.md" "Dockerfile" "docker-compose.yml" "src/*" "*.spec.ts" "*.test.ts" "coverage/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-backend-webapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_90E69328E4E34DB3955A57531B01E0D3 }}